/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuthorsRouteImport } from './routes/admin.authors'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/admin/matches',
  path: '/admin/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/admin/authors',
  path: '/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/matches': typeof MatchesRoute
  '/scoreboard': typeof ScoreboardRoute
  '/timeline': typeof TimelineRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/teams': typeof AdminTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/matches': typeof MatchesRoute
  '/scoreboard': typeof ScoreboardRoute
  '/timeline': typeof TimelineRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/teams': typeof AdminTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/matches': typeof MatchesRoute
  '/scoreboard': typeof ScoreboardRoute
  '/timeline': typeof TimelineRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/teams': typeof AdminTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors'
    | '/matches'
    | '/scoreboard'
    | '/timeline'
    | '/admin/authors'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/login'
    | '/admin/matches'
    | '/admin/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors'
    | '/matches'
    | '/scoreboard'
    | '/timeline'
    | '/admin/authors'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/login'
    | '/admin/matches'
    | '/admin/teams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors'
    | '/matches'
    | '/scoreboard'
    | '/timeline'
    | '/admin/authors'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/login'
    | '/admin/matches'
    | '/admin/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRoute
  MatchesRoute: typeof MatchesRoute
  ScoreboardRoute: typeof ScoreboardRoute
  TimelineRoute: typeof TimelineRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/admin/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/admin/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRoute,
  MatchesRoute: MatchesRoute,
  ScoreboardRoute: ScoreboardRoute,
  TimelineRoute: TimelineRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminTeamsRoute: AdminTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
